-- reset.sql
-- Drops all tables in correct order
 
DROP TABLE Order_Details CASCADE CONSTRAINTS;
DROP TABLE Payment CASCADE CONSTRAINTS;
DROP TABLE Orders CASCADE CONSTRAINTS;
DROP TABLE Menu_Item CASCADE CONSTRAINTS;
DROP TABLE Customer CASCADE CONSTRAINTS;
DROP TABLE Restaurant CASCADE CONSTRAINTS;