-- schema.sql: This file contains all CREATE TABLE statements including primary keys, foreign keys, and constraints

 
CREATE TABLE Customer (
customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR2(100) NOT NULL,
email VARCHAR2(100) UNIQUE,
phone VARCHAR2(15)
);
 
CREATE TABLE Restaurant (
restaurant_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR2(100) NOT NULL,
location VARCHAR2(200)
);
 
CREATE TABLE Menu_Item (
item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
restaurant_id INTEGER NOT NULL,
name VARCHAR2(100) NOT NULL,
price NUMBER(6,2) NOT NULL,
FOREIGN KEY (restaurant_id) REFERENCES Restaurant(restaurant_id)
);
 
CREATE TABLE Orders (
order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
customer_id INTEGER NOT NULL,
restaurant_id INTEGER NOT NULL,
order_date DATE DEFAULT SYSDATE,
status VARCHAR2(20),
FOREIGN KEY (customer_id) REFERENCES Customer(customer_id),
FOREIGN KEY (restaurant_id) REFERENCES Restaurant(restaurant_id)
);
 
CREATE TABLE Order_Details (
order_id INTEGER,
item_id INTEGER,
quantity INTEGER NOT NULL,
PRIMARY KEY (order_id, item_id),
FOREIGN KEY (order_id) REFERENCES Orders(order_id),
FOREIGN KEY (item_id) REFERENCES Menu_Item(item_id)
);
 
CREATE TABLE Payment (
payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
order_id INTEGER UNIQUE,
amount NUMBER(8,2),
payment_method VARCHAR2(50),
payment_date DATE DEFAULT SYSDATE,
FOREIGN KEY (order_id) REFERENCES Orders(order_id)
);
